defaults:
  - model: lcnn
  - metrics: asvspoof
  - datasets: asvspoof_eval
  - dataloader: asvspoof
  - transforms: asvspoof
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "asvspoof_eval" # any name here, can be a dataset name
  prediction_filename: "mmmaevskiy.csv"
  seed: 10
  from_pretrained: "saved/lcnn_cross_entropy_eer/model_best.pth"
